applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"
urlpatterns = [
    path('',
         views.InicioView.as_view(),
         name="inicio-persona"
         ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleado-all'
    ),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado-detail'
    ),
    path(
        'listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name="listar-area"
    ),
    path(
        'listar-empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="listar-empleados-admin"
    ),
    path(
        'modificar/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar'),
    path(
        'eliminar/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar'),
    path(
        'agregar-empleado/',
        views.EmpleadoCreateView.as_view(),
        name="agregar-empleado"
    ),
    ##################################################################



    path(
        'buscar-empleado/',
        views.ListEmpleadoByKword.as_view(),

    ),
    path('habilidades/', views.ListHabilidadesEmpleado.as_view()),


    path('success/', views.SuccesView.as_view(), name='correcto'),


]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.departamento.urls')),
    path('',include('applications.persona.urls')),
    path('',include('applications.home.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento

# Create your models here.

class habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad' #lo que se demuestra en el admin
        verbose_name_plural = 'habilidades'

    def __str__(self):
        return self.habilidad 



class Empleado (models.Model):
    JOB_CHOICES= (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),

    )
    first_name = models.CharField('Nombres',max_length = 150)
    last_name = models.CharField('Apellidos', max_length = 150)
    full_name = models.CharField('Nombres & Apellidos', max_length = 150, blank=True)
    job = models.CharField('trabajo', max_length = 1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', null=True, blank=True)
   #relacion a muchos a muchos
    habilidades  = models.ManyToManyField(habilidades)
    


    class Meta:
        verbose_name = 'Empleado' #lo que se demuestra en el admin
        verbose_name_plural = 'Empleados'

    def __str__(self):
        return self.first_name + ' ' + self.last_name 
    

applications/persona/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)

from .models import Empleado

#form
from .form import *


class InicioView(TemplateView):
    """Pagina de inicio"""
    template_name = "persona/index.html"



# Create your views here.
################################################
############ List View #########################
################################################
# listar todos los empleados de la empresa
class ListAllEmpleados(ListView):
    template_name = 'persona/list-all.html'
    paginate_by= 4



    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
            
        )
        return lista
class ListAllEmpleadosAdmin(ListView):
    template_name = 'persona/list-all-admin.html'
    ordering = 'id'
    paginate_by= 5
    context_object_name='empleado'
    
    model=Empleado



# listar todos los empleados  que pertenecen a un area de la empresa


class ListByAreaEmpleado(ListView):
    """Lista empleados de un area

    Args:
        ListView ([type]): [description]
    """

    template_name = 'persona/list-by-area.html'
    context_object_name='empleados'
    # queryset= Empleado.objects.filter(

    #     departamento__shor_name = 'otro'
    # )

    def get_queryset(self):
        # recoger variables desde url
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista


# listar todos los empleados por palabra clave
class ListEmpleadoByKword(ListView):
    """listar todos los empleados por palabra clave por un buscador html
    """

    template_name = 'persona/list-by-kword.html'
    context_object_name = 'empleados'  # esto es el resultado para pintar en el html

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista

# Listar habilidades de un empleado ManyToMany


class ListHabilidadesEmpleado(ListView):
    model = Empleado
    context_object_name = 'habilidades'
    template_name = 'persona/habilidades.html'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=6)
        return empleado.habilidades.all


################################################
############ Details View #########################
################################################

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detail-empleado.html'


################################################
############ Create View #######################
################################################


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class = EmpleadoForms 
    # fields = ('__all__') #traer los datos
    # fields = [
    #         'first_name', 
    #         'last_name', 
    #         'job', 
    #         'departamento',
    #         'habilidades',
    #         'image',
    #         ]  
    # success_url='.' #recarga la misma pagina
    # recarga la misma pagina
    success_url = reverse_lazy('persona_app:listar-empleados-admin')

    #si los datos del formulario son validos entra a la siguiente función
    def form_valid(self, form):
        #se recupera todos los datos del formulario
        # empleado=form.save() #para que lo guarde en la base de datos
        empleado=form.save(commit=False) #para solo hacer solo la isntancia y no guardar en al base de datos
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView,self).form_valid(form)


class SuccesView(TemplateView):
    template_name = "persona/success.html"

################################################
############ Update View #######################
################################################


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "persona/update.html"
    fields = [
            'first_name', 
            'last_name', 
            'job', 
            'departamento',
            'habilidades',
            ] 
    success_url = reverse_lazy('persona_app:listar-empleados-admin')

    #ecuperar datos desde el formulario por post
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)


################################################
############ Delete View #######################
################################################


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:listar-empleados-admin')

templates/persona/add.html
{% extends '../base.html' %}
{% load widget_tweaks %}
{% block title %}Editar Empleado{% endblock title %}

{% block content %}
<div class="container">
    {% include "../includes/header.html" %}
    <h1>modificar empleado</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Nombres</span>
                    {{form.first_name| add_class:'form-control'| attr:'autocomplete:off'}}

                    <span class="input-group-text" id="inputGroup-sizing-sm">Apellidos</span>
                    {{form.last_name| add_class:'form-control'| attr:'autocomplete:off'}}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Trabajo</span>
                    {{form.job| add_class:'form-control'| attr:'autocomplete:off'}}
                    <span class="input-group-text" id="inputGroup-sizing-sm">Departamento</span>
                    {{form.departamento| add_class:'form-control'| attr:'autocomplete:off'}}

                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Fotografía</span>
                    {{form.image| add_class:'form-control'| attr:'autocomplete:off'}}
                   
                </div>
                <div class=" mb-3">
                    
                    <span class="input-group-text" id="inputGroup-sizing-sm">Habilidades</span>
                    {{form.habilidades|  attr:'autocomplete:off'}}
                </div>

                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>

</div>

{% endblock content %}

templates/persona/delete.html
{% extends '../base.html' %}
{% block title %}
  Eliminar Empleado
{% endblock title %}

{% block content %}
{% include "../includes/header.html" %}
<div class="container">
    <h1>eliminar</h1>

    <form method="POST">
        {% csrf_token %}
        <p>Desea borrar al empleado : {{object.full_name}} </p>
        <button type="submit">Si acepto</button>
        <a href="{% url 'persona_app:listar-empleados-admin' %}" >Cancelar</a>
    </form>
</div>



{% endblock content %}

templates/persona/detail-empleado.html
{% extends '../base.html' %}
{% load widget_tweaks %}
{% block title %}{{object.full_name}}{% endblock title %}

{% block content %}
<div class="container">
    {% include "../includes/header.html" %}
    <h1>Detalle empleado</h1>

    <div class="card" style="width: 18rem;">

        {% if  empleado.image%}
        <img src="{{empleado.image.url}}" class="card-img-top" alt="...">

        {% else %}
        <svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#868e96"></rect><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image
                cap</text>
        </svg>
        {% endif %}


        <div class="card-body">
            <h5 class="card-title">{{empleado.first_name}} {{empleado.last_name}}</h5>
            <p class="card-text">{{empleado.get_job_display}}</p>
            <p class="card-text">{{empleado.departamento.shor_name}}</p>
            <p class="card-text">Habilidades</p>
            <ul>
                {% for h in empleado.habilidades.all %}
                <li>{{h.habilidad}}</li>
                {% endfor %}
            </ul>


        </div>
    </div>






</div>
{% endblock content %}

templates/persona/habilidades.html
{% for h in habilidades %}
    <li>{{h}} </li>
{% endfor %}
    

templates/persona/index.html
{% extends '../base.html' %}}

{% load static  %}
{% block title %}Pagina de inicio, pagina empleados {% endblock title %}


{% block content %}
{% include "../includes/header.html" %}
<!-- imagen de portada -->
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="800" height="70vh" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Marcador de posición: segunda diapositiva" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#666"></rect><text x="50%" y="50%" fill="#444" dy=".3em">Second slide</text></svg>
        </div>
        <div class="carousel-item">
            <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="800" height="400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Marcador de posición: segunda diapositiva" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#666"></rect><text x="50%" y="50%" fill="#444" dy=".3em">Second slide</text></svg>
        </div>
        
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endblock content %}

templates/persona/list-all-admin.html
{% extends '../base.html' %}

{% block content %}
{% include "../includes/header.html" %}

<div class="container">

    <div class="row">

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombres</th>
                    <th scope="col">Apellidos</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Accion</th>
                </tr>
            </thead>
            <tbody>


                {% for e in object_list %}
                <tr>

                    <td scope="row">{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td>
                        <a href=" {% url 'persona_app:modificar' e.id %} " class="btn btn-primary">Editar</a>
                        <a href=" {% url 'persona_app:eliminar' e.id %} " class="btn btn-danger">Eliminar</a>
                    </td>



                </tr>
                {% endfor %}

            </tbody>
        </table>

    </div>
    <div class=" row">
        <div class="col-12 text-end">

            {% if is_paginated %}
            <nav aria-label="Page navigation example  text-start">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                    
                    {% ifequal  pagina  page_obj.number %} 
                    <li class="page-item active"><a class="page-link " href="?page={{pagina}}">{{pagina}}</a></li>
                    {% else %}
                    <li class="page-item "><a class="page-link " href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endifequal %}
                        
                    
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}


        </div>
    </div>
</div>

{% endblock content %}

templates/persona/list-all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for e in object_list %}
          <li>{{e}}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/persona/list-by-area.html
{% extends "../base.html" %}


{% block title %}Departamentos{% endblock title %}

{% block content %}
{% include "../includes/header.html" %}

<div class="container">
    <div class="row ">

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombres</th>
                    <th scope="col">Apellidos</th>
                    <th scope="col">Accion</th>

                </tr>
            </thead>
            <tbody>


                {% for e in empleados %}
                <tr>

                    <td scope="row">{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td><a href=" {% url 'persona_app:empleado-detail' e.id %} " class="btn btn-primary">Ver</a></td>




                </tr>
                {% endfor %}

            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

{% for e in object_list %}
<li>{{e}}</li>
{% endfor %}

</body>

</html>

templates/persona/list-by-kword.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="" method="get">
        {% csrf_token %}
        <input type="text" name="kword" id="kword" placeholder="ingrese el nombre">
        <button type="submit">Buscar</button>
    </form>
    <h2>resultado</h2>
    <ul>
        {% for empleado in empleados %}
        <li>{{empleado}}</li>
        {% endfor %}
    </ul>
</body>

</html>

templates/persona/success.html
<h1>se agrego</h1>

templates/persona/update.html
{% extends '../base.html' %}
{% load widget_tweaks %}
{% block title %}Editar Empleado{% endblock title %}

{% block content %}
<div class="container">
    {% include "../includes/header.html" %}
    <h1>modificar empleado</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Nombres</span>
                    {{form.first_name| add_class:'form-control'| attr:'autocomplete:off'}}

                    <span class="input-group-text" id="inputGroup-sizing-sm">Apellidos</span>
                    {{form.last_name| add_class:'form-control'| attr:'autocomplete:off'}}
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Trabajo</span>
                    {{form.job| add_class:'form-control'| attr:'autocomplete:off'}}
                    <span class="input-group-text" id="inputGroup-sizing-sm">Departamento</span>
                    {{form.departamento| add_class:'form-control'| attr:'autocomplete:off'}}

                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Habilidades</span>
                    {{form.habilidades| add_class:'form-control'| attr:'autocomplete:off'}}
                </div>

                <button type="submit" class="btn btn-primary">Modificar</button>
            </form>
        </div>
    </div>

</div>

{% endblock content %}