applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='crear-departamento'
        ),
    path(
        'listar-departamento/', 
        views.DepartamentoListView.as_view(), 
        name='listar-departamento'
        ),
    
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"
urlpatterns = [
    path('',
         views.InicioView.as_view(),
         name="inicio-persona"
         ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleado-all'
    ),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado-detail'
    ),
    path(
        'listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name="listar-area"
    ),
    path(
        'listar-empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="listar-empleados-admin"
    ),
    path(
        'modificar/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar'),
    path(
        'eliminar/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar'),
    path(
        'agregar-empleado/',
        views.EmpleadoCreateView.as_view(),
        name="agregar-empleado"
    ),
    ##################################################################



    path(
        'buscar-empleado/',
        views.ListEmpleadoByKword.as_view(),

    ),
    path('habilidades/', views.ListHabilidadesEmpleado.as_view()),


    path('success/', views.SuccesView.as_view(), name='correcto'),


]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.departamento.urls')),
    path('',include('applications.persona.urls')),
    path('',include('applications.home.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        imagen-empleado
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href=" {% url 'persona_app:empleado-all' %} " class="nav-link px-2 link-secondary">Listar</a></li>
        <li><a href="{% url 'departamento_app:listar-departamento' %}" class="nav-link px-2 link-dark">Departamentos</a></li>
        <li><a href="{% url 'persona_app:listar-empleados-admin' %} " class="nav-link px-2 link-dark">administrar</a></li>
      
      </ul>

      <div class="col-md-3 text-end">        
        <a href="  {% url 'persona_app:agregar-empleado' %}" class="btn btn-primary">Registrar</a>
        <a href="  {% url 'departamento_app:crear-departamento' %}" class="btn btn-primary">Nuevo.Departamento</a>
      </div>
    </header>
  </div>