applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='crear-departamento'
        ),
    path(
        'listar-departamento/', 
        views.DepartamentoListView.as_view(), 
        name='listar-departamento'
        ),
    
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"
urlpatterns = [
    path('',
         views.InicioView.as_view(),
         name="inicio-persona"
         ),
    path(
        'listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleado-all'
    ),
    path(
        'ver-empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado-detail'
    ),
    path(
        'listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name="listar-area"
    ),
    path(
        'listar-empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="listar-empleados-admin"
    ),
    path(
        'modificar/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar'),
    path(
        'eliminar/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar'),
    path(
        'agregar-empleado/',
        views.EmpleadoCreateView.as_view(),
        name="agregar-empleado"
    ),
    ##################################################################



    path(
        'buscar-empleado/',
        views.ListEmpleadoByKword.as_view(),

    ),
    path('habilidades/', views.ListHabilidadesEmpleado.as_view()),


    path('success/', views.SuccesView.as_view(), name='correcto'),


]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.departamento.urls')),
    path('',include('applications.persona.urls')),
    path('',include('applications.home.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length = 150, )
    shor_name = models.CharField('Nombre Corto', max_length = 50, unique=True)
    anulate = models.BooleanField('Anulado', default=False,)

    def __str__(self):
        return str(self.id) + '-' + self.shor_name
    

    class Meta:
        verbose_name = 'Departamento' #lo que se demuestra en el admin
        verbose_name_plural = 'Departamentos'
        ordering=['-name']
        unique_together=('name','shor_name') #que no se reguistre una combinacion igual 
    

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic.list import ListView


from applications.persona.models import *
from applications.departamento.models import *

from .form import NewDepartamentoForm
# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/list.html"
    context_object_name='departamentos'


class NewDepartamentoView(FormView):
    """NewDepartamentoView definition."""

    template_name = 'departamento/new-departamento.html'
    form_class= NewDepartamentoForm
    success_url= '/'

    def form_valid(self, form):

        #crear una instancia dle modelo departamento
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name= form.cleaned_data['shortname']
        )
        #guardar en la base de datos
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']


        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )

        

        return super(NewDepartamentoView,self).form_valid(form)

templates/departamento/list.html
{% extends "../base.html" %}


{% block title %}Departamentos{% endblock title %}

{% block content %} 
{% include "../includes/header.html" %}

<div class="container">
    <div class="row">

        <table class="table table-hover" class="text-center">
            <thead class="text-center">
                <tr>
                    
                    <th scope="col">Nombre</th>
                    <th scope="col">Nombre Corto</th>
                    <th scope="col"></th>

                </tr>
            </thead>
            <tbody>


                {% for departamento in departamentos %}
                <tr class="text-center">
                    
                    
                   
                    <td>{{departamento.name}}</td>
                    <td>{{departamento.shor_name}}</td>
                   
                    <td><a href=" {% url 'persona_app:listar-area' departamento.shor_name %}  " class="btn btn-primary"> Empleado</a></td>



                </tr>
                {% endfor %}

            </tbody>
        </table>

    </div>
    <div class=" row">
        <div class="col-12 text-end">

            {% if is_paginated %}
            <nav aria-label="Page navigation example  text-start">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                    
                    {% ifequal  pagina  page_obj.number %} 
                    <li class="page-item active"><a class="page-link " href="?page={{pagina}}">{{pagina}}</a></li>
                    {% else %}
                    <li class="page-item "><a class="page-link " href="?page={{pagina}}">{{pagina}}</a></li>
                    {% endifequal %}
                        
                    
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}


        </div>
    </div>
</div>
    
{% endblock content %}  
    
    

templates/departamento/new-departamento.html
{% extends '../base.html' %}
{% load widget_tweaks %}
{% block title %}Nuevo departamento{% endblock title %}

{% block content %}
<div class="container">
    {% include "../includes/header.html" %}
    <h1>modificar empleado</h1>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="POST" >
                {% csrf_token %}
                <h4>Datos Empleado</h4>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Nombres</span>
                    {{form.nombre| add_class:'form-control'| attr:'autocomplete:off'}}

                  
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Apellidos</span>
                    {{form.apellidos| add_class:'form-control'| attr:'autocomplete:off'}}
                  

                </div>
                <h4>Datos Departamento</h4>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Departamento Nombre</span>
                    {{form.departamento| add_class:'form-control'| attr:'autocomplete:off'}}
                   
                </div>
                <div class="input-group mb-3">
                    
                    <span class="input-group-text" id="inputGroup-sizing-sm">Departamento corto</span>
                    {{form.shortname| add_class:'form-control'| attr:'autocomplete:off'}}
                </div>

                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>

</div>

{% endblock content %}